// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIs0ZNpxvtsrS6U4cssuLELkzaGUC76Y4',
    appId: '1:403617176842:web:ccbe1106bfd25cfa4daef3',
    messagingSenderId: '403617176842',
    projectId: 'my-portfolio-d077c',
    authDomain: 'my-portfolio-d077c.firebaseapp.com',
    databaseURL: 'https://my-portfolio-d077c-default-rtdb.firebaseio.com',
    storageBucket: 'my-portfolio-d077c.appspot.com',
    measurementId: 'G-64L846L0LG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSOicWnAWgUUsPwDs4hZFF6xJnSbBeRO0',
    appId: '1:403617176842:android:64883eba27be2ce14daef3',
    messagingSenderId: '403617176842',
    projectId: 'my-portfolio-d077c',
    databaseURL: 'https://my-portfolio-d077c-default-rtdb.firebaseio.com',
    storageBucket: 'my-portfolio-d077c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKwuWM7wbNP2dsJqWaCFaCTAkKQ7cw5OE',
    appId: '1:403617176842:ios:4df765f2f6cc933d4daef3',
    messagingSenderId: '403617176842',
    projectId: 'my-portfolio-d077c',
    databaseURL: 'https://my-portfolio-d077c-default-rtdb.firebaseio.com',
    storageBucket: 'my-portfolio-d077c.appspot.com',
    iosClientId: '403617176842-3tv6uf6l4okl7757v9nj7fc1jirf6a83.apps.googleusercontent.com',
    iosBundleId: 'com.example.etw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKwuWM7wbNP2dsJqWaCFaCTAkKQ7cw5OE',
    appId: '1:403617176842:ios:4df765f2f6cc933d4daef3',
    messagingSenderId: '403617176842',
    projectId: 'my-portfolio-d077c',
    databaseURL: 'https://my-portfolio-d077c-default-rtdb.firebaseio.com',
    storageBucket: 'my-portfolio-d077c.appspot.com',
    iosClientId: '403617176842-3tv6uf6l4okl7757v9nj7fc1jirf6a83.apps.googleusercontent.com',
    iosBundleId: 'com.example.etw',
  );
}
